[default]
src = 'src'
out = 'out'
libs = ['lib']
gas_reports = ['KodexExchange']
solc_version = '0.8.11'
optimizer = true
optimizer_runs = 200
extra-output = ['ir-optimized']

# See more config options https://github.com/gakonst/foundry/tree/master/config
